md5: md5_sample.cpp  md5.cpp
	g++ md5.cpp md5_sample.cpp -o bin/md5_sample.exe && bin/md5_sample  && bin/md5_sample  && bin/md5_sample  && bin/md5_sample  && bin/md5_sample 

sha: sha_sample.cpp  sha256.cpp
	g++ sha256.cpp sha_sample.cpp -o bin/sha_sample.exe && bin/sha_sample && bin/sha_sample && bin/sha_sample && bin/sha_sample && bin/sha_sample 

pymd5: pymd5.pymd5
	python pymd5

rwm: watermark_test_functions.c
	gcc watermark_test_functions.c -o bin/rwm && bin/rwm && bin/rwm && bin/rwm && bin/rwm 
